### ISSUE TITLE
isort ignoring "known_first_party" from pyparsing.toml

### ISSUE THREAD

**Issue by thejcannon** [pre-commit/mirrors-isort#12]
(Every file here underneath "scripts/my_package". I'm in a monorepo. My CWD is `scripts/my_package`)

`.pre-commit-config.yaml`
```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        files: ^scripts/my_package/
        # Needed for the pyproject.toml parsing
        additional_dependencies: [toml]
```

`pyproject.toml`
```toml
[tool.isort]
skip_glob = ".venv/**,tests/snapshots/**"
known_first_party = "my_package"
```

`my_package/foo.py`
```py
import os

import requests

import my_package.bar

# ...
```

Running `isort` locally from the root of this folder tells me everything is good.

Running it via `pre-commit run` wants to relocate `my_package.bar` above `requests`.
