### ISSUE TITLE
It doesn't consider local modules

### ISSUE THREAD

**Issue by vad** [pre-commit/mirrors-isort#4]
I have a local module `a` (`a.py`). Standalone `isort` sorts imports like:

```py
import re  # stdlib

import psycopg2  # third parties

import a  # local
```

I don't know why (problems with working directory?) but this pre-commit plugin sorts it this way instead:

```py
import re

import a
import psycopg2
```

Python 2.7.14, isort 4.3.4.

```yaml
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: flake8
```
