### ISSUE TITLE
Add toml package by default?

### ISSUE THREAD

**Issue by Tenzer** [pre-commit/mirrors-isort#6]
Since isort 4.3.5 and later versions have come out which supports reading the isort configuration from `pyproject.toml` I've seen loads of warnings from the isort hook like the following:

```
/Users/jeppe/.cache/pre-commit/repo2k2s4d5b/py_env-python3.7/lib/python3.7/site-packages/isort/settings.py:292: UserWarning: Found /Users/jeppe/git/<project>/pyproject.toml but toml package is not installed. To configureisort with /Users/jeppe/git/<project>/pyproject.toml, install with 'isort[pyproject]'.
  "isort with %s, install with 'isort[pyproject]'." % (file_path, file_path)
```

This is despite isort being configured to have the "toml" package installed via:
```yaml
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.9
    hooks:
      - id: isort
        additional_dependencies:
          - toml
```

We are using Black for code formatting and have the configuration for that inside our `pyproject.toml` files.

Confusingly the warnings are only printed when another check gives errors, and are often printed numerous times (presumably for each `isort` invocation), which makes it quite prominent in the resulting output, hiding the real cause of errors being printed.

I was wondering if it would make sense to add the "toml" library to `setup.py` - and possible some of the other [extra packages](https://github.com/timothycrosley/isort/blob/master/setup.py#L24-L29) to this hook by default, as it doesn't appear to me like the `additional_dependencies` section functions right - or at least how I expect it to.

**Comment by asottile** [comment]
I'm unable to reproduce this claim:

> This is despite isort being configured to have the "toml" package installed via:

### without:

```yaml
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.9
    hooks:
    -   id: isort
```

```console
$ pre-commit  run --all-files
seed isort known_third_party.............................................Passed
isort....................................................................Failed
hookid: isort

Files were modified by this hook. Additional output:

Fixing /tmp/astpretty/setup.py
Fixing /tmp/astpretty/astpretty.py
Fixing /tmp/astpretty/tests/astpretty_test.py
/home/asottile/.cache/pre-commit/repomlvlju3c/py_env-python3/lib/python3.6/site-packages/isort/settings.py:292: UserWarning: Found /tmp/astpretty/pyproject.toml but toml package is not installed. To configureisort with /tmp/astpretty/pyproject.toml, install with 'isort[pyproject]'.
  "isort with %s, install with 'isort[pyproject]'." % (file_path, file_path)
```

### with

```yaml
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.9
    hooks:
    -   id: isort
        additional_dependencies: [toml]
```

```console
$ pre-commit  run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-isort:toml.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
seed isort known_third_party.............................................Passed
isort....................................................................Failed
hookid: isort

Files were modified by this hook. Additional output:

Fixing /tmp/astpretty/setup.py
Fixing /tmp/astpretty/astpretty.py
Fixing /tmp/astpretty/tests/astpretty_test.py

```

----

as this repo is a simple mirror of `isort` it would be incorrect to install other things by default.  you can always add the functionality you need by setting `additional_dependencies`
