### ISSUE TITLE
Pathspec 'sha' did not match any file(s)

### ISSUE THREAD

**Issue by Jawdeath** [pre-commit/mirrors-isort#7]
I've added code from the example to my conf file add when trying to make a commitment , I see "Errors: pathspec 'sha' did not match any file(s) known to git". Also tried to specify 4.3.17 version, the result is the same. Here is my config:
```yaml
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 4.3.17
    hooks:
    -   id: isort
```
