### ISSUE TITLE
pre-commit isort hook ignores .isort.cfg, namely skip section

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [pre-commit/mirrors-isort#9]
ISort allows specifying in commit in skip section of configuration the files, which should be excluded from sorting imports.

However, when such file was modified due to different reason (for example, doc string reformating), and is being processed by pre-commit, then isort reformats this file, and ignores, that it is being marked to be skipped by isort in config (I observed this behaviour when using isort in combination with seed-isort-config

This makes isort pre-commit hook unusable for my project

**Comment by asottile** [comment]
next you'll need to provide a full reproduction -- "doesn't work" isn't a bug report.  this should (at a minimum) include a `pre-commit` configuration, some sample files, and your isort configuration.

also note that there isn't anything special going on here -- pre-commit just invokes `isort` so you're probably seeing `isort` not reading your configuration.  that said, even though I don't use isort myself, I can probably take a look into the issue on `isort`'s side

looking forward to your more complete report!

**Comment by serhiy-yevtushenko** [comment]
pre-commit config:

```
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    -   id: isort

-   repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
        - id: autoflake
          args: ['--in-place', '--remove-unused-variable']

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length, "120", "."]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
      files: \.(json)$
    - id: check-yaml
    - id: fix-encoding-pragma
      args: [--remove]
    - id: flake8
      additional_dependencies: [flake8-blind-except, flake8-builtins, flake8-rst-docstrings, flake8-logging-format]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.711
    hooks:
    -   id: mypy

-   repo: https://github.com/myint/docformatter
    rev: v1.1
    hooks:
    - id: docformatter
      name: docformatter
      description: 'Formats docstrings to follow PEP 257.'
      entry: docformatter
      args: [-i, --wrap-summaries, "120", --wrap-description, "120"]
      language: python
      types: [python]

-   repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0
    hooks:
    - id: pydocstyle
      name: pydocstyle
      description: pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.
      entry: pydocstyle
      language: python
      types: [python]

```
.isort.cfg
```
[settings]
line_length=120
skip=embeddings/compute_similarities_parts2GAs.py, embeddings/prepare_data.py, embeddings/similarity_model_training_parts2GAs.py, embeddings/word_embedding_training_parts2GAs.py
known_first_party=tautils,parts_2_ga
known_third_party=elasticsearch,fuzzywuzzy,gensim,glove,keras,mock,more_itertools,numpy,pandas,pylint,scipy,setuptools,tensorflow
indent='    '
multi_line_output=0
sections = STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
```

#Steps for reproduction:


I have a file prepare_data.py in embeddings config

I do following steps:
1. Modify formatting in data via docformmatter:
(one could go to embedding folder and execute:
`docformatter -i --wrap-summaries 120 --wrap-description 120 prepare_data.py)`

2. Try to commit file:
On first attempt, two pre-commit hooks fail (black and isort)

The problem for me is that isort should not touch this file at all (as it stays in skip variable in `.isort.cfg`)

On second attempt, the modified file is committed (and import order in it is now incorrect)

**Comment by asottile** [comment]
It's often useful in computing to boil down a complicated reproduction to a "minimal reproducible (compilable) example" -- your example doesn't really include enough information to reproduce exactly so I tried to come up with my own case separately.

## minimal case **involving pre-commit**

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
```

### .isort.cfg

```ini
[settings]
known_third_party = astpretty
skip=t2.py
```

### t.py

```python
import os

import astpretty
```

### t2.py

```python
import astpretty
import os
```

### runtime

there's nothing special about other hooks making modifications, I suspect if you isolate your case you'll find that black has nothing to do with it (?)  anyway here's what I have:

```console
$ pre-commit  run --all-files
seed isort known_third_party.............................................Passed
isort....................................................................Failed
hookid: isort

Files were modified by this hook. Additional output:

Fixing /tmp/x/t2.py

```

but let's try and narrow that down further since pre-commit isn't doing anything special here...

## reproduction **without pre-commit**

same files as above, but this time we'll invoke `isort` directly:

```console
$ isort -i t.py t2.py
Fixing /tmp/x/t2.py
$ git diff
diff --git a/t2.py b/t2.py
index 6dd3f37..22dcc45 100644
--- a/t2.py
+++ b/t2.py
@@ -1,2 +1,3 @@
-import astpretty
 import os
+
+import astpretty
```

so much for `skip` I guess?

**Comment by asottile** [comment]
that said, even though `isort` has a bug here, you can always work around broken exclusion settings by using `pre-commit`'s own settings

trying this configuration on for size appears to work:

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        exclude: ^t2\.py$
```

### `.isort.cfg`

```ini
[settings]
known_third_party = astpretty
```

### output

```console
$ pre-commit  run --all-files
seed isort known_third_party.............................................Passed
isort....................................................................Passed
```
